<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-21 06:52
=======
# Generated by Django 4.1.7 on 2023-03-20 04:57
>>>>>>> e5194187ca670e5365bb8348d2e3c7b939b0cc8f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
